### ISSUE TITLE
Class loading failing due undefined symbol in the shared library. 

### ISSUE THREAD

**Issue by harish2704** [tursodatabase/libsql-php#8]
I just tried to test this php library and it failed with following error

```
PHP Fatal error:  Uncaught FFI\Exception: Failed loading '/tmp/libsql-php-test/vendor/turso/libsql/src/../lib/x86_64-unknown-linux-gnu/liblibsql.so' (/tmp/libsql-php-test/vendor/turso/libsql/src/../lib/x86_64-unknown-linux-gnu/liblibsql.so: undefined symbol: sqlite3_wal_manager) in /tmp/libsql-php-test/vendor/turso/libsql/src/Database.php:24
Stack trace:
#0 /tmp/libsql-php-test/vendor/turso/libsql/src/Database.php(24): FFI::cdef()
#1 /tmp/libsql-php-test/vendor/turso/libsql/src/Database.php(40): Libsql\getFFI()
#2 /tmp/libsql-php-test/vendor/composer/ClassLoader.php(576): include('...')
#3 /tmp/libsql-php-test/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#4 /tmp/libsql-php-test/libsqltest.php(6): Composer\Autoload\ClassLoader->loadClass()
#5 {main}
  thrown in /tmp/libsql-php-test/vendor/turso/libsql/src/Database.php on line 24
```

## Steps I followed.
1.  In a fresh directory, run `composer require turso/libsql`
2. Created a test file as follows 
```
<?php
require './vendor/autoload.php';

use Libsql\Database;

$db = new Database(
    path: 'local.db',
    url: getenv('TURSO_DATABASE_URL'),
    authToken: getenv('TURSO_AUTH_TOKEN'),
    syncInterval: 1000
);

```
3. Tried to run the php file `php libsqltest.php`

## My OS / dev environment 
1. OS: `Fedora Linux 41 (KDE Plasma)`
2. php version 
```
PHP 8.3.14 (cli) (built: Nov 19 2024 15:14:23) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.3.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.14, Copyright (c), by Zend Technologies
```
3. Output of `composer show`
```
$ composer show 
turso/libsql 0.1.1 libSQL bindings for PHP
```

**Comment by levydsa** [comment]
@harish2704 Can you try the `@dev` version? I just pushed a fix

**Comment by harish2704** [comment]
Hi @levydsa , It is working now. Thank you for your quick response.
